[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.133"

[dependencies.reqwest]
version = "0.12.11"
default-features = false
features = ["blocking", "rustls-tls"]
